---
sample_rate: 44100
segment_seconds: 3.0
train:
    source_types:
        vocals:
            musdb18:
                hdf5s_directory: "bytedance_hdf5"
                key_in_hdf5: "vocals"
                hop_seconds: 0.1
        accompaniment:
            musdb18:
                hdf5s_directory: "bytedance_hdf5"
                key_in_hdf5: "accompaniment"
                hop_seconds: 0.1
    indexes: "bytedance_indexes/sr=44100,vocals-accompaniment.pkl"
